- hotswap-agent-core/src/main/java/org/hotswap/agent/HotswapAgent.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java
Instead of having the hotswap-agent.properties be in the resources
folder, it is now possible to specify which external file will have
the HotSwapAgent configuration.
-javaagent:hotswapagent/hotswap-agent.jar=propertiesFilePath=hotswapagent/hotswap-agent.properties
> Allow configuration to be loaded from an external file

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/HotswapSpringInvocationHandler.java
I solved the problem by intercepting InvocationTargetException and then
throwing the cause exception.
> Fixed UndeclaredThrowableException in Spring plugin.

- plugin/hotswap-agent-webobjects-plugin/src/main/java/org/hotswap/agent/plugin/webobjects/HotswapWebObjectsPlugin.java
The interface declaration is not mandatory so it may be required even without it.
> Clear validation cache on every reload

- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/WatcherFactory.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/AbstractNIO2Watcher.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/EventDispatcher.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/HotswapWatchFileEvent.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/PathPair.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/TreeWatcherNIO.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/WatcherNIO2.java
Refactored watcher service so a different implementation is used in
unices and windows. In windows the FILE_TREE modifier is used and sub directories are watched by the service (no need to register each directory individually)
> Windows watcher service

- README.md
- hotswap-agent-core/README.md
- hotswap-agent-core/pom.xml
- hotswap-agent-core/src/main/java/org/hotswap/agent/HotswapAgent.java
- hotswap-agent/pom.xml
Sometime it's useful to attach to running JVM process and reload class
with version containing more writing to log entries using Hotswapper
plugin. This helps to investigate rarely heppenning issues, because
restarting JVM with agent doesn't guarantee reproducing of the issues.
PFA example how to attach hotswap-agent.jar to running JVM process:
[AgentRunner.java.txt](https://github.com/HotswapProjects/HotswapAgent/files/475203/AgentRunner.java.txt)
> Added support to attach agent runtime to JVM process

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/scanner/ClassPathScanner.java
In my deployment in WebLogic 12 the classloader returns the JAR files of
the web application prefixed with "zip:" instead of "jar:". That prevents
us from loading our custom plugin.
The jar files are taken from the standard WAR location (WEB-INF/lib/)
Example of an error:
```
<BEA-000000> <HOTSWAP AGENT: 6:3:56.322 WARNING (org.hotswap.agent.util.scanner.ClassPathScanner) - Unknown resource type of file zip:/opt/web-app/WEB-INF/lib/dev-tools.jar!/com/acme/hotswap/agent/plugin/acme>
```
> Modify the ClassPathScanner to support URIs prefixed with "zip:"

- plugin/hotswap-agent-hibernate-plugin/src/main/java/org/hotswap/agent/plugin/hibernate/HibernateTransformers.java
Add the other spring implementation class that was missing. 
See https://github.com/spring-projects/spring-framework/blob/4.2.x/spring-orm/src/main/java/org/springframework/orm/jpa/vendor/HibernateJpaVendorAdapter.java#L91.
> Add Support for Hibernate 4.2 in Spring. 

- plugin/hotswap-agent-tomcat-plugin/pom.xml
i have added some flexibility and (really) minor documentation to build the tomcat-plugin against versions 6.x and 7.x+ of tomcat, which have different artifactId. perhaps create a tomcat6 only plugin (for compat reasons) and newer versions with the new artifactId? just a thought ...
> tomcat artifact flexibility

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/HotswapTransformer.java
As I understand the code in question, a normal regex is required here. Spring and others also support Ant like notation, where the double asterisk ** can cause problems here. This is a proposed quick-fix, But I don't know if this has side-effects.
> Fix proposal for #78 and #165

- hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/hotswapper/HotswapperPlugin.java
In some environments (especially Gradle + Kotlin + Mac OS), the old class files are removed before newly compiled files are written to file system. In this case WatchService generate ENTRY_DELETE and ENTRY_CREATE instead of just ENTRY_MODIFY. That means HotswapperPlugin does not detect changes in class files.
The change in the pull request makes the plugin listen to ENTRY_CREATE as well.
> HotswapperPlugin: listen also to FileEvent.CREATE

- plugin/hotswap-agent-wicket-plugin/README.md
- plugin/hotswap-agent-wicket-plugin/pom.xml
- plugin/hotswap-agent-wicket-plugin/src/main/java/org/hotswap/agent/plugin/wicket/WicketPlugin.java
- pom.xml
Initial implementation of a Wicket hotswap plugin.
Currently only clears `Localizer` cache when property files are changed.
> Add Wicket plugin

- plugin/hotswap-agent-plugins/pom.xml
I missed adding the new plugin to the agents `pom.xml` in  #278.
> Add Wicket plugin dependency to agents POM

- plugin/hotswap-agent-cxf-plugin/src/main/java/org/hotswap/agent/plugin/cxf/jaxrs/CxfJAXRSTransformer.java
When using CxfJAXRS plugin two issue where found in our project:
1. Duplicate method creation when patching JAXRSCdiResourceExtension
Solution: remove not necessary method registration.
2. If application initialize AbstractJAXBProvider before invocation of JAXRSCdiResourceExtension#load or ResourceUtils#createClassResourceInfo initialization failed as plugin method registerJAXBProvider is invoked on not initialized plugin.
Solution: Initilialize plugin also on AbstractJAXBProvider#init method.
> Fixed issues in plugin CxfJAXRS

- plugin/hotswap-agent-spring-plugin/pom.xml
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/SpringPluginTest.java
Removed the need to cleanup after every test by keeping a list of swapped classes.
> cleanup spring plugin unit test

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/ReflectionHelper.java
- hotswap-agent-parent/pom.xml
- plugin/hotswap-agent-spring-plugin/run-tests.sh
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/ResetSpringStaticCaches.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvc/SampleRestController.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvc/SpringMvcTest.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvcHotswap/SampleRestController2.java
To fix Spring MVC Hotswap, some additional static caches have to be cleared. As the spring MVC code and unit test code would not compile under old spring versions, drop support for old spring versions as discussed in #349.
> Fix Spring MVC Hotswap, Drop Support for old Spring Versions

- hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java
Hello,
This is an idea that was discussed in the other pull request. This code override settings from file with -D. It copies all the other arguments and HA does not mind. I could filter the relevant settings but I think it would make things more complex.
I tried overriding the constructor of HotswapProperties.java but, sadly, the settings were overidden by the internal .properties file.
Take care,
Leonard
> Overriding properties from command line using -D

- plugin/hotswap-agent-jackson-plugin/README.md
- plugin/hotswap-agent-jackson-plugin/pom.xml
- plugin/hotswap-agent-jackson-plugin/run-tests.sh
- plugin/hotswap-agent-jackson-plugin/src/main/java/org/hotswap/agent/plugin/jackson/JacksonPlugin.java
- plugin/hotswap-agent-jackson-plugin/src/test/java/org/hotswap/agent/plugin/jackson/JacksonPluginTest.java
- plugin/hotswap-agent-jackson-plugin/src/test/java/org/hotswap/agent/plugin/jackson/model/TestModel1.java
- plugin/hotswap-agent-jackson-plugin/src/test/java/org/hotswap/agent/plugin/jackson/model/TestModel2.java
- plugin/hotswap-agent-jackson-plugin/src/test/resources/hotswap-agent.properties
- plugin/hotswap-agent-plugins/pom.xml
- pom.xml
Jackson is used by spring mvc to convert model result to json string.
Jackson saves some type cache in internal to improve performance.
For example, there is _rootDeserializers cache field in com.fasterxml.jackson.databind.ObjectMapper. These caches cause new field can not be read from json or be written to json.
> Add jackson plugin

- hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/bytecode/ClassFile.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/jdk/JdkPlugin.java
The `java.beans.Introspector#declaredMethodCache` was removed as of JDK 13 (https://github.com/openjdk/jdk13u/commit/921b46738e0c3aaa2bf8c62e0accb0a5056190d3) which caused a reload exception in the `JdkPlugin`.
> Handle missing declaredMethodCache in JdkPlugin

- plugin/hotswap-agent-plugins/pom.xml
- plugin/hotswap-agent-weblogic-plugin/README.md
- plugin/hotswap-agent-weblogic-plugin/pom.xml
- plugin/hotswap-agent-weblogic-plugin/src/main/java/org/hotswap/agent/plugin/weblogic/WeblogicPlugin.java
- pom.xml
A weblogic plugin based on comment https://github.com/HotswapProjects/HotswapAgent/issues/164#issuecomment-701276011 by https://github.com/Kladdkaka .
I have translated the original Kotlin code to Java and integrated with Hotswapagent project as a plugin.
It successfully reloads existing classes and adds new classes based extraClasspath.
Tested happy path with Weblogic 12c.
- put a hotswapagent.properties file in WEB-INF/classes of war deployed to Weblogic
- inside the file set the extraClasspath property
- I had trouble to find a good matching oraclejdk and dcevm pair to work correctly with weblogic on amd64. For now only these two seem to work OK
- oraclejdk 1.8.0_05 + dcevm installer-light-jdk8u5.52.jar (25.5-b02-dcevmlight-58)
- oraclejdk 1.8.0_25 + dcevm …
> Weblogic plugin

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/IOUtils.java
In my environment(Linux 5.17 + dcevm8u28208), Mybatis's mapperLocation is `org.springframework.core.io.FileSystemResource` and the `getInputStream()` return `sun.nio.ch.ChannelInputStream`. `org.hotswap.agent.util.IOUtils#extractFileNameFromInputStream` doesn't working for it. 
I'm sorry that I didn't run the test, but I am really confused which JDK version should I use.
> fix Mybatis plugin not reload

- plugin/hotswap-agent-proxy-plugin/src/main/java/org/hotswap/agent/plugin/proxy/ProxyPlugin.java
- plugin/hotswap-agent-proxy-plugin/src/main/java/org/hotswap/agent/plugin/proxy/ReloadJavaProxyCommand.java
sometimes the jdk proxy class dont' realize the interface,
```java
java.lang.AbstractMethodError: com.test.HelloThriftService.hello(Ljava/lang/String;)Ljava/lang/String;
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
```
> fix java.lang.AbstractMethodError in com.sun.proxy.$Proxy117 #429

- hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginManager.java
Hello,
I want to push some modified classes (local project files) to serveral remote application servers to autoHotswap these classes. Thus I need to check the reload result by the hotswap-agent.log.  
Now it just throws the exception which can only be found in console output,  therefore I add the error log.
Is it useful to this projects?
> Add errMsg when autoHotswap reload fail

- plugin/hotswap-agent-resteasy-plugin/pom.xml
- plugin/hotswap-agent-resteasy-registry-plugin/pom.xml
Upgrade resteasy-jaxrs 3.0.14.Final to 3.11.0.Final for vulnerability fix:
- [CVE-2017-7561](https://www.oscs1024.com/hd/MPS-2017-10357)
- [CVE-2016-6347](https://www.oscs1024.com/hd/MPS-2017-4384)
> fix(sec): upgrade resteasy-jaxrs to 3.11.0.Final

- plugin/hotswap-agent-spring-plugin/pom.xml
There are 1 security vulnerabilities found in org.springframework:spring-context 5.3.18
- [CVE-2022-22968](https://www.oscs1024.com/hd/CVE-2022-22968)
Upgrade org.springframework:spring-context from 5.3.18 to 5.3.19 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade org.springframework:spring-context to 5.3.19

- hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/jvm/ClassInitPlugin.java
The name of the static field in Enum class is "$VALUES" instead of "ENUM$VALUES".
By the way, i can't run tests ClassInitTest, it throws exception `throw new IllegalStateException("Plugin manager is not correctly initialized `, maybe because of junit running order or other issue.
But i have tested this change by some tricky methods.
> Fix enum field update

- plugin/hotswap-agent-undertow-plugin/pom.xml
There are 1 security vulnerabilities found in io.undertow:undertow-core 2.2.17.Final
- [CVE-2021-3597](https://www.oscs1024.com/hd/CVE-2021-3597)
Upgrade io.undertow:undertow-core from 2.2.17.Final to  for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>
> fix(sec): upgrade io.undertow:undertow-core to 

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/classloader/URLClassLoaderHelper.java
The second parameter type in `findResource()` and `findResources()`  in sun.misc.URLClassPath is a primitive type. Without the following enhancement, watchResources in hotswap-agent.properties won't work.
```java
(parameterTypes[1] == Boolean.TYPE || parameterTypes[1] == Boolean.class))
```
> the 2nd parameter could be primitive type (boolean.class)

- plugin/hotswap-agent-tomcat-plugin/src/main/java/org/hotswap/agent/plugin/tomcat/TomcatPlugin.java
There's a regression introduced to stop `extraClasspath` and `watchResources` work on apache tomcat 7. This change make it work again.
> fix: make extraClasspath and watchResources work for tomcat7x

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/ReflectionHelper.java
- plugin/hotswap-agent-tomcat-plugin/src/main/java/org/hotswap/agent/plugin/tomcat/TomcatPlugin.java
Tomcat's WebappClassLoader has a big refactor since 7.0.65. This fix makes extra class and resource work on 7.0.65 and later too.
1. Make sure `repositories` and `files` are updated correctly, even they are moved into WebappClassLoaderBase.
2. In org.apache.catalina.loader.WebappClassLoaderBase#findResourceInternal(java.lang.String, java.lang.String, boolean), a fullPath is calculated:
```java
String fullPath = repositories[i] + path;
```
It leads to double '/' between repository and path. This double '/' works fine with tomcat's builtin DirContext but start to fail work with WatchResourcesClassLoader. This resource name must have to be normalized before passed it to WatchResourcesClassLoader.
> fix: extra class and resource won't work on tomcat 7.0.65 and after

- hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java
- plugin/hotswap-agent-tomcat-plugin/src/main/java/org/hotswap/agent/plugin/tomcat/WebappLoaderTransformer.java
In a spring boot web application, TomcatPlugin cannot locate the 'hotswap-agent.properties' packaged in WEB-INF/classes. This change can make both SpringPlugin and TomcatPlugin locate the right properties file instead of the one packaged in hotswapagent.jar. 
```properties
extraClasspath=/Users/iluo/tmp/tutorial/spring-mvc-basic-1/target/classes
watchResources=/Users/iluo/tmp/tutorial/spring-mvc-basic-1/src/main/resources
webappDir=/Users/iluo/tmp/tutorial/spring-mvc-basic-1/src/main/webapp
LOGGER=debug
```
This change also patches org.apache.catalina.core.StandardWrapper so that Tomcat always runs in development mode and JSP compilation works in development mode too. It is necessary since Spring Boot configures embedded tomcat in production mode.
To reproduce the issue, write a simple …
> support jsp update in spring boot

- plugin/hotswap-agent-proxy-plugin/src/test/java/org/hotswap/agent/plugin/proxy/TestClassAdapter.java
fix "java.lang.UnsupportedOperationException: This feature requires ASM7" when running junit tests in hotswap-agent-proxy-plugin
> Fixed bugs in junit tests for hotswap-agent-proxy-plugin module

- plugin/hotswap-agent-spring-plugin/run-tests.sh
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/ResetBeanFactoryCaches.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/SpringPlugin.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/PropertiesRefreshCommand.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanDefinitionScannerTransformer.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/placeholder/Item1.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/placeholder/Item2.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/placeholder/PlaceholderTest.java
- plugin/hotswap-agent-spring-plugin/src/test/resources/item.properties
- plugin/hotswap-agent-spring-plugin/src/test/resources/itemChanged.properties
- plugin/hotswap-agent-spring-plugin/src/test/resources/placeholderContext.xml
Given the spring XML configuration, and Spring beans 'Store' and 'Item' below:
ioc-context-by-type.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">
<bean class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
<property name="location" value="classpath:item.properties"/>
</bean>
<bean id="item" class="com.baeldung.store.ItemImpl1">
<property name="name" value="${item.name}"/>
</bean>
<bean id="xml-store-by-autowire-type" class="com.baeldung.store.Store" autowire="byType">
</bean>
</beans>
```
item.properties
```properties …
```
> Placeholder support

- hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginManager.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/util/HotswapTransformer.java
when we configure excludedClassLoaderPatterns in hotswap-agent.properteis, the extraClasspath is still prepended to URLClassPath of URLClassLoader
> enhance exclude classloader

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/SpringPlugin.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanRefreshCommand.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlFileRefreshCommand.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/placeholder/Item2WithoutValue.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/placeholder/PlaceholderTest.java
This change is mainly to make refreshing work when individual bean class is changed for XML based Spring application. Without it, refreshing will not be detected by SpringPlugin therefore hotswap will not happen at all.
In this change, I also refactor all commands (MergeableCommand's impls) in this plugin to make the implementation better.
> support reloading when individual bean class is changed for xml based spring app

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/ResetBeanFactoryCaches.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/ResetBeanFactoryPostProcessorCaches.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/placeholder/AnnotationConfigTest.java
- plugin/hotswap-agent-spring-plugin/src/test/resources/placeholderContextWithoutAnnotationConfig.xml
Currently HotswapAgent's spring plugin cannot hotswap when `<context:annotation-config/>` is switched on and off. For example, given the XML configuration file below:
```xml
<beans>
<bean id="item" class="com.baeldung.store.ItemImpl2"/>
</beans>
```
when `<context:annotation-config/>` is added:
```xml
<beans>
<context:annotation-config/>
<bean id="item" class="com.baeldung.store.ItemImpl2"/>
</beans>
```
The annotations defined in ItemImpl2 should be honored but they are not, for example: `@Value` will not be injected when annotation config is turned on. This proposed change make `<context:annotation-config/>` can be able to hotswap as expected
> make <context:annotation-config/> able to hotswap

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/HotswapTransformer.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/util/ReflectionHelper.java
- hotswap-agent-core/src/main/java/org/hotswap/agent/watch/nio/AbstractNIO2Watcher.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/SpringPlugin.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/processor/ConfigurationClassPostProcessorAgent.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/processor/ConfigurationClassPostProcessorTransformer.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reader/AnnotatedBeanDefinitionReaderAgent.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reader/AnnotatedBeanDefinitionReaderTransformer.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reader/ComponentClassRefreshCommand.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reader/ComponentClassTransformer.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/redefine/BeanDefinitionResolver.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/redefine/BeanDefinitionResolverSupport.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanDefinitionScannerTransformer.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/SpringBeanTransformer.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/SpringBeanWatchEventListener.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/utils/RegistryUtils.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/ConfigurationTest.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/ConfigurationXmlTest.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/beans/BeanA.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/beans/BeanB.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/beans/BeanC.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/beans/Config.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/configs/Config1.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/configs/Config2.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/configuration/configs/Config3.java
- plugin/hotswap-agent-spring-plugin/src/test/resources/configuration.xml
- plugin/hotswap-agent-spring-plugin/src/test/resources/hotswap-agent.properties
The current spring plugin doesn't have `@Configuration` support which's used quite popularly in today's modern spring app. 
a) Scenario#1: Declare component-scan in XML file, and there is a configuration class under the defined package.
```xml
<beans xmlns="http://www.springframework.org/schema/beans"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:context="http://www.springframework.org/schema/context"
xsi:schemaLocation="http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-3.0.xsd http://www.springframework.org/schema/context https://www.springframework.org/schema/context/spring-context.xsd">
<context:component-scan base-package="org.hotswap.agent.plugin.spring.configuration.beans"/>
</beans>
```
```java
package …
```
> Spring @Configuration  support

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/HotswapTransformer.java
I experienced a deadlock recently, which is shown below:
```
Found one Java-level deadlock:
=============================
"Thread-11":
waiting to lock monitor 0x00007fab28008800 (object 0x00000006003b8eb0, a org.hotswap.agent.config.PluginManager),
which is held by "Thread-44"
"Thread-44":
waiting to lock monitor 0x00007fab5091b900 (object 0x000000060060b7b8, a c.t.p.CustomClassLoader),
which is held by "Thread-11"
Java stack information for the threads listed above:
===================================================
"Thread-11":
at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:181)
- waiting to lock <0x00000006003b8eb0> (a org.hotswap.agent.config.PluginManager)
at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransfo …
```
> potential deadlock

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/XmlBeanDefinitionScannerAgent.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/init/FooBean.java
- plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/xml/init/InitTest.java
- plugin/hotswap-agent-spring-plugin/src/test/resources/initContext-1.xml
- plugin/hotswap-agent-spring-plugin/src/test/resources/initContext-2.xml
This proposed change call  the code below to init singleton bean eagerly since user's code may not have chance to call getBean() again so that user's spring bean has no chance to be hotswaped even though its corresponding bean definition has already been updated.
```java
factory.preInstantiateSingletons();
```
> support preInstantiateSingletons

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/ProxyReplacer.java
The right way is :  the classloader of the bean or org.springframework.beans.factory.support.AbstractBeanFactory.getBeanClassLoader, but not the classLoader of the beanFactry.class.
> fix: the ClassLoader of BeanFactory.class is not the same as the classLoader of bean

- hotswap-agent-parent/pom.xml
- pom.xml
If we don't specify, it will use default plugin version.
> specify maven deploy plugin version

- plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/transformers/PropertySourceLoaderTransformer.java
fix: UnmodifiedMap has some transient fields which cause problems
In org.springframework.boot.env.PropertiesPropertySourceLoader ：
```
public List<PropertySource<?>> load(String name, Resource resource) throws IOException {
List<Map<String, ?>> properties = loadProperties(resource);
if (properties.isEmpty()) {
return Collections.emptyList();
}
List<PropertySource<?>> propertySources = new ArrayList<>(properties.size());
for (int i = 0; i < properties.size(); i++) {
String documentNumber = (properties.size() != 1) ? " (document #" + i + ")" : "";
propertySources.add(new OriginTrackedMapPropertySource(name + documentNumber,
Collections.unmodifiableMap(properties.get(i)), true));
}
return propertySources;
}
```
If we use Collections.unmodifiableMap to create the map, it will cause the map …
> fix: UnmodifiedMap has some transient fields which cause problems

- plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/env/HotswapSpringProperties.java
- plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/env/HotswapSpringReloadMap.java
- plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/env/ListPropertySourceReloader.java
fix: when the application-testing.properties is a empty file, it will throw npe
> fix npe issue

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/core/AutowiredAnnotationProcessor.java
#530 
The org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor#postProcessPropertyValues is removed in spring6, we should use org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor#postProcessProperties to replace it.
> fix #530, fix noSuchMethod in spring6

- hotswap-agent-core/src/main/java/org/hotswap/agent/util/HotswapTransformer.java
I'm running into an issue: 
If a classLoader is excluded that configured as excludedClassLoaderPatterns, I expect that all the class of this ClassLoader will not be transformed,  but I find the classes that annotated as @OnClassLoadEvent are transformed.
I want to accomplish the goal above, so I post this pr, but I'm not sure if it's the right,  especially if it has any impact on others.
> If we configure excludedClassLoaderPatterns, maybe we should skip transform

- plugin/hotswap-agent-plugins/pom.xml
- plugin/hotswap-agent-sponge-plugin/README.md
- plugin/hotswap-agent-sponge-plugin/pom.xml
- plugin/hotswap-agent-sponge-plugin/src/main/java/org/hotswap/agent/plugin/sponge/ReloadListenersCommand.java
- plugin/hotswap-agent-sponge-plugin/src/main/java/org/hotswap/agent/plugin/sponge/SpongePlugin.java
- pom.xml
Adds a [Sponge](https://spongepowered.org/) module which is a Minecraft modding platform. Enables the support of reloading plugin registrations on the fly when a listener class is modified.
Not entirely sure if this is in the scope of the repository but giving it a go.
> Add Sponge module

- plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java
Updates the Vaadin plugin to delegate reload operations to the Vaadin Hotswapper component introduced in Vaadin 24.5.
Backward compatibility with older Vaadin versions is preserved by detecting the absence of the Hotswapper component and falling back to the original behavior.
Part of vaadin/flow#19261
> feat: add support for Vaadin Hotswapper

- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/MyBatisRefreshCommands.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/ConfigurationProxy.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/SpringMybatisConfigurationProxy.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/ConfigurationCaller.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/MyBatisTransformers.java
- When MyBatis runs in Spring-MyBatis mode, it encounters a NullPointerException and the reload fails.[#556](https://github.com/HotswapProjects/HotswapAgent/issues/556)，[#550](https://github.com/HotswapProjects/HotswapAgent/issues/550),，[#538](https://github.com/HotswapProjects/HotswapAgent/issues/538),
- When MyBatis runs in Spring-MyBatis mode,there is no need to cache configuration-related data。The related reload operations are handled by SpringMybatisConfigurationProxy
- When MyBatis runs in Spring-MyBatis mode,we only need to use SpringMybatisConfigurationProxy for reloading. Refreshing the ConfigurationProxy is not meaningful.The same applies in the opposite case.
> Fix the issue with MyBatis-Spring integration where MyBatis reloading is not functioning properly and results in a NullPointerException.

- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/MyBatisPlugin.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/MyBatisRefreshCommands.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/ConfigurationProxy.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/SpringMybatisConfigurationProxy.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/ConfigurationCaller.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/MyBatisTransformers.java
- plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java
1.Feature Added: Enable SQL reload when using annotation-based SQL.
2.Feature Added: Enable reload when there are changes in entity classes, such as result entity or parameter entity classes.
3.Refactor MyBatisTransformers code to improve readability and maintainability.
> New Feature Added to MyBatis Plugin: Annotation SQL Reload Functionality

- plugin/hotswap-agent-mybatis-plugin/pom.xml
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/MyBatisPlugin.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/MyBatisRefreshCommands.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/ConfigurationProxy.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/SpringMybatisConfigurationProxy.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/ConfigurationCaller.java
- plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/MyBatisTransformers.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/MyBatisPluginAnnoTest.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/MybatisSpringBootTest.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/springboot/Application.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/springboot/BootUser.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/springboot/BootUserMapper.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/springboot/BootUserMapper2.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/testBeansHotswap/UserMapper.java
- plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/testBeansHotswap/UserMapper2.java
- plugin/hotswap-agent-mybatis-plugin/src/test/resources/application.properties
- plugin/hotswap-agent-mybatis-plugin/src/test/resources/db/bootuser.sql
- plugin/hotswap-agent-mybatis-plugin/src/test/resources/org/hotswap/agent/plugin/mybatis/mybatis-config-anno.xml
- plugin/hotswap-agent-mybatis-plugin/src/test/resources/swapXML/BootUserMapper1.xml
- plugin/hotswap-agent-mybatis-plugin/src/test/resources/swapXML/BootUserMapper2.xml
- plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java
1.Add unit tests for #558:: When using annotation-based SQL, verify the reload after the class has been modified.
2.Add MybatisSpringBootTest to verify reload behavior in Spring Boot applications
- Verify issue #557: Application can successfully reload without configuring mybatis.config-location.
- Verify issue #558: Application can successfully reload when annotated SQL classes change without configuring mybatis.config-location.
> Add unit test code for the MyBatis plugin.

- plugin/hotswap-agent-tomcat-plugin/pom.xml
- plugin/hotswap-agent-tomcat-plugin/src/main/java/org/hotswap/agent/plugin/tomcat/TomcatPlugin.java
- **Updated Tomcat Version**: The pom.xml for the Tomcat plugin has been updated to use Tomcat version 10.1.28, aligning the plugin with the latest versions of Tomcat.
- **Fix for Tomcat Version Detection:** The method resolveTomcatMajorVersion in `TomcatPlugin.java` has been adjusted to correctly detect the major version of Tomcat by using `split("\\.")` instead of `substring(0, 1)`. This change allows proper handling of multi-digit versions like `10.x`.
**Justification**:
- **Compatibility with Tomcat 10.x**: This update ensures that the Hotswap Agent plugin properly supports Tomcat 10.x, which is essential for projects that have migrated to the latest Tomcat versions.
- **Improved Version Handling Logic**: The previous implementation assumed the major version would be a single digit …
> fix: tomcat major version detection

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/files/XmlBeanDefinitionScannerAgent.java
Spring Plugin: use AbstractBeanDefinitionReader#getRegistry instead of AbstractBeanDefinitionReader#getBeanFactory which is deprecated in Spring Framework 6.0
> Spring Plugin: use AbstractBeanDefinitionReader#getRegistry instead of AbstractBeanDefinitionReader#getBeanFactory

- plugin/hotswap-agent-jackson-plugin/src/main/java/org/hotswap/agent/plugin/jackson/JacksonPlugin.java
Most other plugins seems to stay quiet when doing normal reload operations and everything works but with any Spring Boot app you quickly have a console full of nothing but
```
HOTSWAP AGENT: 10:22:06.352 INFO (org.hotswap.agent.plugin.jackson.JacksonPlugin) - Reloaded Jackson.
HOTSWAP AGENT: 10:22:24.210 INFO (org.hotswap.agent.plugin.jackson.JacksonPlugin) - Reloaded Jackson.
HOTSWAP AGENT: 10:23:00.600 INFO (org.hotswap.agent.plugin.jackson.JacksonPlugin) - Reloaded Jackson.
```
> Change Jackson reload logging to debug

- plugin/hotswap-agent-mybatis-plus-plugin/src/main/java/org/hotswap/agent/plugin/mybatisplus/transformers/MyBatisPlusTransformers.java
running mybatis project throw exception 
Caused by: org.hotswap.agent.javassist.bytecode.DuplicateMemberException: duplicate field: $$ha$factoryBean
at org.hotswap.agent.javassist.bytecode.ClassFile.testExistingField(ClassFile.java:677)
at org.hotswap.agent.javassist.bytecode.ClassFile.addField(ClassFile.java:657)
at org.hotswap.agent.javassist.CtClassType.addField(CtClassType.java:1432)
at org.hotswap.agent.javassist.CtClass.addField(CtClass.java:1117)
at org.hotswap.agent.plugin.mybatisplus.transformers.MyBatisPlusTransformers.addBuilderField(MyBatisPlusTransformers.java:127)
at org.hotswap.agent.plugin.mybatisplus.transformers.MyBatisPlusTransformers.patchSqlSessionFactoryBuilder(MyBatisPlusTransformers.java:140)
... 78 more
> fix non mybatisplus project SqlSessionFactoryBuilder transform twice issue

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/SpringPlugin.java
The Spring plugin is not compatible with the versions before 3.1.0（See run-tests.sh of SpringPlugin） So why not use the Versions annotation to specify the version of Spring in which the enhancements are enabled? 
By the way, for Spring 6.x, the Spring CGLIB name policy has changed. Thus,  org.hotswap.agent.plugin.spring.getbean.ProxyReplacer#register is not compatible with the versions after 6.0.
see org.springframework.cglib.core.SpringNamingPolicy#SPRING_LABEL
```java
/**
/*
* Copyright 2002-2023 the original author or authors.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      https://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable …
```
> use Versions annotation to specify the version of Spring in which the enhancements are enabled

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/ProxyReplacer.java
It seems like that the Spring plugin should be gotten by PluginManager. If the classLoader which load the Spring framework in the application is not the same with the classLoader which load the hotswap agent, the SpringPlugin.basePackagePrefixes will be empty(whether the spring.basePackagePrefix is configured or not).
> use PluginManager#getPlugin to get SpringPlugin in ProxyReplacer#register

- plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reload/SpringBeanReload.java
I noticed that from time to time the plugin tries reloading abstract beans which causes a total mess in the console and in my specific case crashes everything so that I need to restart the server completely.
> Prevented initializing of abstract beans in SpringBeanReload::preInstantiateSingleton

- plugin/hotswap-agent-glassfish-plugin/src/main/java/org/hotswap/agent/plugin/glassfish/WebappClassLoaderTransformer.java
Field "resourceEntries", [used by glassfish-plugin](https://github.com/HotswapProjects/HotswapAgent/blob/2df6bf6b2b37df378e25ae9c6b27bb3c469235f8/plugin/hotswap-agent-glassfish-plugin/src/main/java/org/hotswap/agent/plugin/glassfish/WebappClassLoaderTransformer.java#L40), [was replaced](https://github.com/eclipse-ee4j/glassfish/commit/256d73b4c5f1ebefc08044a7d7c1772792afa893#diff-0141ffd3d9718ae19012299c13f1c8db7fec76927fd5d82a2bfc8d227b69668dR188-L194) with resourceEntryCache in GlassFish 7 and higher.
In this PR plugin is adapted to this change.
Stay compatible with previous versions of GlassFish.
> Adapt to GlassFish 7
