HotswapProjects/HotswapAgent

plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/EnhancerProxyCreater.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/HotswapSpringInvocationHandler.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/ProxyReplacer.java
This fixed #91 for me. There was a issue with using proxy instances as map keys in Spring TransactionSynchronizationManager class.
=> Sping plugin fixes

hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java, hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginManager.java, hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginRegistry.java, hotswap-agent-core/src/main/java/org/hotswap/agent/util/scanner/ClassPathScanner.java, hotswap-agent-parent/pom.xml, hotswap-agent/pom.xml
Attempt to fix issue #97 by using "System" method when the ClassLoader is null and correctly set boot-class-path for (among other things, fix exceptions when running tests).
=> Issue 97: Handle null ClassLoader

hotswap-agent-core/src/main/java/org/hotswap/agent/config/LogConfigurationHelper.java, hotswap-agent-core/src/main/resources/hotswap-agent.properties
Adding ability to specify that log messages should be appended to the configured LOGFILE (this allowed me to write to the same log file that Log4J does)
=> Adding LOGFILE.append configuration option

plugin/hotswap-agent-resteasy-registry-plugin/README.md, plugin/hotswap-agent-resteasy-registry-plugin/pom.xml, plugin/hotswap-agent-resteasy-registry-plugin/run-tests.sh, plugin/hotswap-agent-resteasy-registry-plugin/src/main/java/org/hotswap/agent/plugin/resteasy/RefreshRegistryCommand.java, plugin/hotswap-agent-resteasy-registry-plugin/src/main/java/org/hotswap/agent/plugin/resteasy/ResteasyRegistryPlugin.java, pom.xml, run-tests.sh
=> Resteasy registry plugin

plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/ResetRequestMappingCaches.java
Due to restructure in spring code, new fields need to be accessed to trigger web mapping handler reload.
Post Spring 4.2, the code in `AbstractHandlerMethodMapping` has been restructured. They have replaced `urlMap` & `handlerMethods` class properties with an inner class `MappingRegistry`. So now, `mappingLookup` and `urlLookup` in `MappingRegistry` need to be cleared instead.
=> fix #90 - added support for spring 4.2+

README.md, hotswap-agent/pom.xml, plugin/hotswap-agent-log4j2-plugin/README.md, plugin/hotswap-agent-log4j2-plugin/pom.xml, plugin/hotswap-agent-log4j2-plugin/src/main/java/org/hotswap/agent/plugin/log4j2/Log4j2Plugin.java, plugin/hotswap-agent-log4j2-plugin/src/test/resources/hotswap-agent.properties, pom.xml
* Add Log4j2 automatic reconfiguration plugin
=> Log4j2 plugin

hotswap-agent-core/src/main/java/org/hotswap/agent/logging/AgentLoggerHandler.java
Also using this format the time stamps will not change length during the day.
=> Use a timestamp format that is closer to ISO8601

plugin/hotswap-agent-hibernate-plugin/src/main/java/org/hotswap/agent/plugin/hibernate/HibernateTransformers.java
=> Only clear metadata cache if field exists

.travis.deploy.sh, .travis.settings.xml, .travis.yml
=> Autodeploy snapshot from master to Maven / Sonatype

README.md
=> Add name to hotswap contributors

README.md, plugin/hotswap-agent-freemarker-plugin/README.md, plugin/hotswap-agent-freemarker-plugin/pom.xml, plugin/hotswap-agent-freemarker-plugin/src/main/java/org/hotswap/agent/plugin/freemarker/FreeMarkerPlugin.java, plugin/hotswap-agent-plugins/pom.xml, pom.xml
Add Apache FreeMarker support - FreeMarker plugin that clears the introspection cache on class redefine
=> Add Apache FreeMarker plugin

hotswap-agent-core/src/main/java/org/hotswap/agent/util/signature/ClassSignatureComparerHelper.java
I've changed the error message siganture by signature
=> Fix error message (siganture)

plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java
Update the plugin to reflect changes in Vaadin 14 and 15.
=> Vaadin 14 compatibility

plugin/hotswap-agent-spring-plugin/pom.xml, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/ClassSwappingRule.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/SpringPluginTest.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvc/SampleRestController.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvc/SpringMvcApplication.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvc/SpringMvcTest.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/mvcHotswap/SampleRestController2.java
As far as I could see, there was no test for Spring MVC, so I created one.
=> Unit test for Spring MVC

hotswap-agent-parent/pom.xml, plugin/hotswap-agent-spring-plugin/pom.xml, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/SpringPluginTest.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/testBeans/BeanService.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/testBeans/BeanServiceImpl.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/testBeans/BeanServiceNoAutowireImpl.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/testBeansHotswap/BeanServiceImpl2.java
@Inject was mentioned in #300 as not to work. This unit test verifies it works.
=> add test for javax.inject

plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinIntegration.java, plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java
=> Vaadin plugin: fix loading of VaadinIntegration class, and default route log message

README.md
Corrected spelling of 'which'.
=> Updated document

plugin/hotswap-agent-vaadin-plugin/pom.xml, plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinIntegration.java, plugin/hotswap-agent-vaadin-plugin/src/main/java/org/hotswap/agent/plugin/vaadin/VaadinPlugin.java
Drops support for older versions
=> fix!: Make compatible with Vaadin 23 and 24

plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanDefinitionScannerAgent.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanRefreshCommand.java
when refresh class, resolve bean definition with start-up classloaer.
=> resolve bean definition with start-up classloaer

plugin/hotswap-agent-mybatis-plugin/pom.xml, plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/MyBatisRefreshCommands.java, plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/proxy/SpringMybatisConfigurationProxy.java, plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/MyBatisTransformers.java, plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/SqlSessionFactoryBeanCaller.java, plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/MyBatisPluginTest.java, plugin/hotswap-agent-mybatis-plugin/src/test/java/org/hotswap/agent/plugin/mybatis/MybatisSpringTest.java, plugin/hotswap-agent-mybatis-plugin/src/test/resources/spring-mybatis.xml
when application  use mybatis-spring, SqlSessionFactory create by SqlSessionFactoryBean, not XMLConfig.
=> mybatis support mybatis-spring

hotswap-agent-core/pom.xml, hotswap-agent-parent/pom.xml
upgrade maven-source-plugin and move it from hotswap-agent-core to hotswap-agent-parent
=> enhance source code deployment

hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java, hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/watchResources/WatchResourcesPlugin.java, hotswap-agent-core/src/main/java/org/hotswap/agent/util/classloader/URLClassPathHelper.java
JDK builti-n classloaders are changed to: 
* jdk.internal.loader.ClassLoaders$BootClassLoader
* jdk.internal.loader.ClassLoaders$PlatformClassLoader
* jdk.internal.loader.ClassLoaders$AppClassLoader
This change enables extraClasspath and watchResources work not only on URLClassLoader but also on  jdk.internal.loader.ClassLoaders
=> make extraClasspath and watchResources work on java11 and java17

hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginConfiguration.java, plugin/hotswap-agent-tomcat-plugin/src/main/java/org/hotswap/agent/plugin/tomcat/TomcatPlugin.java
Today I figured out that I introduce an incorrect implementation to locate tomcat's plugin configuration in HotswapProjects/HotswapAgent#472. Sorry about it.
This change rollbacks the change made in org.hotswap.agent.config.PluginConfiguration and use the better way in TomcatPlugin to locate the plugin configuration.
=> init tomcat's plugin configuration correctly.

plugin/hotswap-agent-plugins/pom.xml, plugin/hotswap-agent-thymeleaf-plugin/README.md, plugin/hotswap-agent-thymeleaf-plugin/pom.xml, plugin/hotswap-agent-thymeleaf-plugin/src/main/java/org/hotswap/agent/plugin/thymeleaf/ThymeleafPlugin.java, pom.xml
add a thymeleaf plugin to clear TemplateManager's cache when its parseAndProcess gets called.
=> thymeleaf plugin

hotswap-agent-core/src/main/java/org/hotswap/agent/util/classloader/URLClassPathHelper.java
when it run at idea, it will throw error:
```
Exception in thread "main" java.lang.ClassNotFoundException: com.intellij.rt.execution.application.AppMainV2$Agent
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ../src/java.instrument/share/native/libinstrument/JPLISAgent.c line: …
```
=> [Fix] when multiple agent is used, it will threw error

plugin/hotswap-agent-spring-plugin/pom.xml, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/ResetTransactionAttributeCaches.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanDefinitionScannerAgent.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/MyBatisConfig.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/StudentMapper.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/StudentService.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/StudentTransactionalService1.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/StudentTransactionalService2.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/TransactionalApplication.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/transactional/TransactionalTest.java
There is currently no feature that supports Spring `@Transactional`, so I created this PR and provided the ut
=> Spring @Transactional support

hotswap-agent-core/src/main/java/org/hotswap/agent/util/AnnotationHelper.java, plugin/hotswap-agent-cxf-plugin/src/main/java/org/hotswap/agent/plugin/cxf/jaxrs/CxfJAXRSCommand.java, plugin/hotswap-agent-cxf-plugin/src/main/java/org/hotswap/agent/plugin/cxf/jaxrs/CxfJAXRSPlugin.java
Add support for Jakarta and fix bug with infinite execution of CxfJAXRSCommand.java, as the HashCode implementation was not correct. 
I did not find a template for PRs, so I just created one. Would be cool if this could be merged, such that I do not need to maintain my own fork.
=> CxfJAXRS Plugin

hotswap-agent-core/src/main/java/org/hotswap/agent/util/classloader/ClassLoaderDefineClassPatcher.java
fix: the super class and interfaces should patch to target classloader before the current class
=> fix: the super class and interfaces should patch to target classloader 

plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/testBeans/iabpp/BeanServiceCreator.java
it compiled failed, should implements the method of interface. 
In  spring 5.x, it is used default method that contains default implements.
=> fix unit test in spring 4.3

plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/SpringBootPlugin.java, plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/listener/PropertySourceChangeBootListener.java, plugin/hotswap-agent-spring-boot-plugin/src/main/java/org/hotswap/agent/plugin/spring/boot/listener/PropertySourceChangeListener.java, plugin/hotswap-agent-spring-boot-plugin/src/test/java/org/hotswap/agent/plugin/spring/boot/properties/PropertiesChangeMockListener.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/listener/SpringEventSource.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/listener/SpringListener.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reload/SpringChangedAgent.java
1. make reloading of beanFactory sequential, the root of beanFactory has hight priority.
2. optimize the event filter: if the parent beanFactory of event is the same as beanFactory of listener, it will trigger the event
=> enhance the spring and spring boot plugin

plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/core/ResetBeanPostProcessorCaches.java
```
@RestController
@RequestMapping("/test")
public class TestController {
@Resource
@Qualifier("helloTestService")
private TestService testService;
}
```
when I modify the value of Qualifier, it cannot work.  
The reason is that CommonAnnotationBeanPostProcessor contains cache that we can't clear.  @Autowired works well because we have cleared the cache of AutowiredAnnotationBeanPostProcessor
=> fix: need clear CommonAnnotationBeanPostProcessor

hotswap-agent-core/src/main/java/org/hotswap/agent/annotation/handler/PluginClassFileTransformer.java, hotswap-agent-core/src/main/java/org/hotswap/agent/annotation/handler/WatchEventCommand.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/core/BeanFactoryProcessor.java
1. reduce spring log: after reloading happened, then print log
2. when the class is transformed failed, then should print the classLoader info.
=> optimize log 

plugin/hotswap-agent-spring-plugin/pom.xml, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/SpringPlugin.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reload/BeanFactoryAssistant.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/transformers/BeanFactoryTransformer.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/transformers/InitDestroyAnnotationBeanPostProcessorTransformer.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/transformers/support/InitMethodEnhance.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/ClassSwappingRule.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/BeanInitTest.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/CommonTestBackupBean.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/CommonTestBean.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitMethodBean1.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitMethodBean2.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitMethodBean3.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitMethodBean4.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitMethodBeanConfiguration.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitializingBean1.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitializingBean2.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitializingBean3.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/InitializingBean4.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/PostConstructorBean1.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/PostConstructorBean2.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/PostConstructorBean3.java, plugin/hotswap-agent-spring-plugin/src/test/java/org/hotswap/agent/plugin/spring/lifecycle/beaninit/PostConstructorBean4.java, plugin/hotswap-agent-spring-plugin/src/test/resources/hotswap-agent.properties, run-tests.sh
=> [enhance] when reload spring bean, if some exception happened when executing init method, we should catch it and print the log

plugin/hotswap-agent-zk-plugin/src/main/java/org/hotswap/agent/plugin/zk/ZkPlugin.java
=> java.lang.NoSuchMethodException for org.zkoss.zel.BeanELResolver.__resetCache() in ZKPlugin

plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/transformers/MyBatisTransformers.java, plugin/hotswap-agent-mybatis-plugin/src/main/java/org/hotswap/agent/plugin/mybatis/util/ClassUtils.java, plugin/hotswap-agent-mybatis-plus-plugin/pom.xml, plugin/hotswap-agent-mybatis-plus-plugin/run-tests.sh, plugin/hotswap-agent-mybatis-plus-plugin/src/main/java/org/hotswap/agent/plugin/mybatisplus/MyBatisPlusPlugin.java, plugin/hotswap-agent-mybatis-plus-plugin/src/main/java/org/hotswap/agent/plugin/mybatisplus/transformers/MyBatisPlusTransformers.java, plugin/hotswap-agent-mybatis-plus-plugin/src/test/java/org/hotswap/agent/plugin/mybatisplus/BaseTest.java, plugin/hotswap-agent-mybatis-plus-plugin/src/test/java/org/hotswap/agent/plugin/mybatisplus/MyBatisPlusSpringBootTest.java
After the increase, the supported versions range from 3.2.0 to 3.5.7.
=> Increase the supported versions for MyBatis-Plus. 

README.md
Add Intellij HotSwapHelper plugin in IDE part.
=> Add Intellij HotSwapHelper plugin.

README.md, hotswap-agent-core/src/main/java/org/hotswap/agent/HotswapAgent.java, plugin/hotswap-agent-mybatis-plus-plugin/src/main/java/org/hotswap/agent/plugin/mybatisplus/transformers/MyBatisPlusTransformers.java
make user easyier to use for disable some plugins.
=> Support disable plugins by vm option -DdisablePlugin=xxxxx

.github/workflows/maven.yml, plugin/hotswap-agent-mybatis-plus-plugin/pom.xml, plugin/hotswap-agent-mybatis-plus-plugin/src/test/java/org/hotswap/agent/plugin/mybatisplus/MyBatisPlusPluginTest.java, plugin/hotswap-agent-mybatis-plus-plugin/src/test/java/org/hotswap/agent/plugin/mybatisplus/MyBatisPlusSpringBootTest.java
The reason is that the dependency scope in MyBatis plugin has been changed to provided. Therefore, it needs to be reintroduced in MyBatisPlus plugin .
=> fix mybatisplus plugin tests

plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/core/ResetBeanPostProcessorCaches.java, plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/reload/SpringBeanReload.java
=> fix: Clear Spring caches for beans created using createBean
